---total units sold by brand----

select sum(f.units_sold) [Total_Units],p.brand [Brand] from salesfact f
left join productdim p on f.product_key = p.product_key
group by p.brand order by sum(f.units_sold) DESC

----total units sold by brand and product subcategory---

select sum(f.units_sold) [Total_Units],
p.product_category[prods_by_subcat],
p.brand from salesfact f Left Join productdim p
on f.product_key = p.product_key
group by p.product_category,p.Brand order by sum(f.units_sold) DESC


---rev generated by productcategory


select product_category,cast(sum(sales_amount) as int) [tot sales] from salesfact f
left join productdim p on
f.product_key = p.product_key
group by product_category

